enable lu_op
ROCmSoftwarePlatform/tensorflow-upstream pull request #1433
Opened 2021-08-25 22:42 UTC by micmelesse

This enables the LU op for rocm. It tests it during the single gpu tests. Credit to @stevenireeves for code to compile the op.

2021-08-26 18:28 UTC, stevenireeves requested changes
See the comment below.

2021-08-26 18:28 UTC, stevenireeves commented on tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh
> +      -//tensorflow/python/kernel_tests:lu_op_test \
You should remove this line. These '-' tells bazel to ignore these tests.

2021-08-26 18:29 UTC, micmelesse commented on tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh
> +      -//tensorflow/python/kernel_tests:lu_op_test \
Got it. Thanks.

2021-08-26 18:32 UTC, micmelesse commented on tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh
> +      -//tensorflow/python/kernel_tests:lu_op_test \
fixed.

2021-08-26 19:17 UTC, stevenireeves approved these changes

2021-08-26 21:05 UTC, stevenireeves commented
jenkins : retest Ubuntu-GPU-single please

2021-08-27 00:59 UTC, stevenireeves commented
@micmelesse looks good to merge.

2021-08-27 01:18 UTC, micmelesse commented
@stevenireeves  Should this be upstreamed?

2021-08-27 01:18 UTC, merged

2021-08-27 02:11 UTC, stevenireeves commented
@micmelesse let's upstream this change after my PR (https://github.com/tensorflow/tensorflow/pull/51423) goes in. I'll keep you updated.