Develop upstream sync 230619
ROCmSoftwarePlatform/tensorflow-upstream pull request #2133
Opened 2023-06-19 13:36 UTC by draganmladjenovic

2023-06-20 08:15 UTC, i-chaochen requested changes
@draganmladjenovic  Good fix! please upstream this commit 👍

2023-06-20 08:15 UTC, i-chaochen requested changes
@draganmladjenovic  Good fix! please upstream this commit as well 👍

2023-06-20 08:17 UTC, i-chaochen requested changes
@draganmladjenovic  Good fix! 👍  please upstream this commit as well.

2023-06-20 16:26 UTC, draganmladjenovic commented
retest Ubuntu-CPU please

2023-06-20 17:32 UTC, draganmladjenovic commented
retest Ubuntu-CPU please

2023-06-21 17:24 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-21 19:18 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-21 23:13 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-22 00:17 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-22 08:27 UTC, i-chaochen commented
retest Ubuntu-CPU please

2023-06-22 12:14 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-22 13:04 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-22 13:48 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-22 14:12 UTC, i-chaochen commented on tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
This is from PR https://github.com/tensorflow/tensorflow/commit/992a68adde1810756f2930f57e6108f891fa7e16

2023-06-22 18:06 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-23 05:58 UTC, draganmladjenovic commented
retest Ubuntu-GPU-single please

2023-06-23 10:46 UTC, i-chaochen approved these changes

2023-06-23 13:58 UTC, merged