Update SYNC_UPSTREAM.md
ROCmSoftwarePlatform/tensorflow-upstream pull request #2544
Opened 2024-05-14 06:09 UTC by mmakevic-amd

Added instructions for the event when weekly sync takes too long to merge, as well as debugging tips.

2024-05-14 11:57 UTC, i-chaochen requested changes

2024-05-14 11:57 UTC, i-chaochen commented on rocm_docs/SYNC_UPSTREAM.md
> +
As we discussed, I think we should have something like this:

> Synchronization should be performed on a weekly basis. Even if it has taken more than 2 weeks (>2) to merge the PR, the next weekly sync should first sync in the middle week between the last one and current one, and then sync the current week.

> For example, if the last weekly-sync PR is 3 weeks ago (2024-04-29), and this weekly-sync (supposed to be 2024-05-13) should start from 2024-05-06, and it needs another weekly-sync at 2024-05-13.

> This way, long breaks (e.g. one month) between syncs will be avoided.

2024-05-15 15:30 UTC, hsharsha commented on rocm_docs/SYNC_UPSTREAM.md
> +* Repeat until the required commit is found
You can also provide reference to https://confluence.amd.com/display/~cchen104/XLA+hotfix+track to cherry-pick XLA hot fixes if the build breaks in xla

2024-05-17 11:05 UTC, i-chaochen approved these changes

2024-05-19 20:38 UTC, i-chaochen commented
retest Ubuntu-GPU-single please
retest Ubuntu-GPU-multi please

2024-06-02 15:39 UTC, merged